import { StyleSheet } from "react-native";
import { colors, width, height, Fonts } from "../../config";

export default StyleSheet.create({ 
    container:{
        backgroundColor:colors.white,
        alignItems:'center',
        justifyContent:'center',
        width:width,
        height:height*0.9,
        padding:5,
    },
    flatlistContainer:{
        flexDirection:'row'
    },
    leftContainer:{
        margin:10,
    },
    eventImage:{
        width:100,
        height:100,
        borderRadius:10,
    },
    rightContainer:{
        margin:10,
    },
    titleText:{
        fontFamily:Fonts.Bold,
        color:colors.black,
        fontWeight:'600',
        fontSize:18,
        lineHeight:27,
        margin:5,
    },
    participant:{
        marginLeft:5,
    },
    buttonContainer:{
        flexDirection:'row',
        borderWidth:1,
        borderRadius:25,
        borderColor:'#BDBDBD',
        alignItems:'center',
        justifyContent:'space-between',
        width:145,
        height:35,
        padding:6,
        margin:5,
    },
    buttonText:{
        fontFamily:Fonts.Medium,
        fontWeight:'400',
        fontSize:14,
        lineHeight:18,
        color:'#898989',
    },
    touchableContainer:{
        alignItems:'center',
        justifyContent:'center',
        height:height*0.1,
    },
    seemoreText:{
        color:colors.gray,
        fontFamily:Fonts.Medium,
        fontWeight:'600',
        fontSize:20,
        lineHeight:24,
        margin:5,
    },
    directionImage:{
        width:22,
        height:11,
    },
 });